import typer
import logging
import json
from pathlib import Path

from autosub.pipeline.transcribe import main as transcribe_main
from autosub.pipeline.format import main as format_module
from autosub.pipeline.translate import main as translate_module

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s:%(levelname)s:%(name)s: %(message)s"
)
logger = logging.getLogger(__name__)

app = typer.Typer(help="AutoSub AI Toolchain CLI")


@app.callback()
def main():
    pass


@app.command()
def transcribe(
    video_path: Path = typer.Argument(
        ..., help="Path to the input video or audio file"
    ),
    output: Path = typer.Option(
        Path("transcript.json"),
        "--out",
        "-o",
        help="Path to save the output JSON transcript",
    ),
    language: str = typer.Option(
        "ja-JP",
        "--language",
        "-l",
        help="Language code for transcription (e.g. ja-JP, en-US)",
    ),
    vocab: list[str] = typer.Option(
        None,
        "--vocab",
        "-v",
        help="Custom context terminology to increase probability of recognition (can be passed multiple times).",
    ),
    vocab_file: Path = typer.Option(
        None,
        "--vocab-file",
        help="Path to a JSON file containing an array of custom vocabulary strings.",
    ),
):
    """
    Extracts audio from a video and transcribes it using Google Cloud Speech-to-Text (Chirp 3).
    """
    logger.info(f"Starting transcription pipeline for: {video_path}")

    # Combine CLI vocab and JSON vocab
    final_vocab = list(vocab) if vocab else []
    if vocab_file:
        try:
            with open(vocab_file, "r", encoding="utf-8") as f:
                file_vocab = json.load(f)
                if not isinstance(file_vocab, list):
                    raise ValueError(
                        "JSON vocab file must contain an array of strings."
                    )
                final_vocab.extend(str(item) for item in file_vocab)
        except Exception as e:
            logger.error(f"Failed to load vocab file {vocab_file}: {e}")
            raise typer.Exit(code=1)

    try:
        result = transcribe_main.transcribe(video_path, output, language, final_vocab)
        logger.info(f"Success! Saved {len(result.words)} words to {output}")
    except Exception as e:
        logger.error(f"Error during transcription: {e}")
        raise typer.Exit(code=1)


@app.command()
def format(
    input_transcript: Path = typer.Argument(
        ...,
        help="Path to the input transcript.json file generated by the transcribe command.",
        exists=True,
        dir_okay=False,
    ),
    out: Path = typer.Option(
        None,
        "--out",
        help="Path to save the generated output .ass file (defaults to original.ass in the same directory).",
    ),
):
    """
    Step 2: Merges an audio transcript JSON into properly timed subtitle lines and generates a .ass file.
    """
    if not out:
        out = input_transcript.with_name("original.ass")

    try:
        format_module.format_subtitles(input_transcript, out)
    except Exception as e:
        logger.error(f"Error during formatting: {e}")
        raise typer.Exit(code=1)


@app.command()
def translate(
    input_ass: Path = typer.Argument(
        ...,
        help="Path to the original .ass file generated by the format command.",
        exists=True,
        dir_okay=False,
    ),
    out: Path = typer.Option(
        None,
        "--out",
        help="Path to save the translated .ass file (defaults to translated.ass in the same directory).",
    ),
    engine: str = typer.Option(
        "vertex",
        "--engine",
        "-e",
        help="Translation engine to use ('vertex' or 'cloud-v3').",
    ),
    prompt: str = typer.Option(
        None, "--prompt", "-p", help="System prompt to guide the LLM translation."
    ),
    prompt_file: Path = typer.Option(
        None,
        "--prompt-file",
        help="Path to a text/markdown file containing the system prompt.",
    ),
    target_lang: str = typer.Option("en", "--target", help="Target language code."),
    source_lang: str = typer.Option("ja", "--source", help="Source language code."),
    bilingual: bool = typer.Option(
        False,
        "--bilingual/--replace",
        help="Include original text on top, or replace completely.",
    ),
):
    """
    Step 3: Translates a .ass subtitle file using the configured Translation Engine.
    """
    if not out:
        out = input_ass.with_name("translated.ass")

    final_prompt = prompt
    if prompt_file:
        try:
            with open(prompt_file, "r", encoding="utf-8") as f:
                final_prompt = f.read().strip()
        except Exception as e:
            logger.error(f"Failed to read prompt file {prompt_file}: {e}")
            raise typer.Exit(code=1)

    try:
        translate_module.translate_subtitles(
            input_ass,
            out,
            engine=engine,
            system_prompt=final_prompt,
            target_lang=target_lang,
            source_lang=source_lang,
            bilingual=bilingual,
        )
    except Exception as e:
        logger.error(f"Error during translation: {e}")
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
